services:
  scraper:
    build:
      dockerfile: ./docker/scraper.Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/news_fusion
    container_name: news-fusion-scraper
  web:
    build:
      dockerfile: ./docker/server.Dockerfile
    restart: always
    ports:
      - "4782:4782"
    expose:
      - "4782"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/news_fusion
    container_name: news-fusion-server
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_fusion
    volumes:
      - ./data:/var/lib/postgresql/data
    container_name: news-fusion-db
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    container_name: news-fusion-qdrant
