services:
  web:
    build:
      dockerfile: ./docker/server.Dockerfile
    restart: always
    ports:
      - "4782:4782"
    expose:
      - "4782"
    volumes:
      # the data folder is mounted to the container
      - ./data:/app/data
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/news_fusion
      - QDRANT_CONNECTION_STRING=http://qdrant:6333
    container_name: news-fusion-server
  postgres:
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_fusion
    volumes:
      - ./data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    container_name: news-fusion-db
  qdrant:
    image: qdrant/qdrant:latest-unprivileged
    restart: always
#    ports:
#      - "6333:6333"
#      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    container_name: news-fusion-qdrant
