# This docker-compose is for development purposes only

name: news-fusion-dev
services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_fusion
    volumes:
      - /etc/news-fusion/pg:/var/lib/postgresql/data
    ports:
      - "5042:5432"
    container_name: news-fusion-db-dev
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6003:6333"
      - "6004:6334"
    volumes:
      - /etc/news-fusion/qdrant:/qdrant/storage:z
    container_name: news-fusion-qdrant-dev
  redis:
    image: redis:alpine
    container_name: news-fusion-redis-dev
    volumes:
      - /etc/news-fusion/redis:/data
    ports:
      - "6379:6379"
