# Development purposes only
name: news-fusion-dev

services:
  # Postgres is used for storing the RSS feed data
  postgres:
    container_name: news-fusion-pg-dev
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_fusion
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data

  # Qdrant is used for storing the embeddings
  qdrant:
    container_name: news-fusion-qdrant-dev
    image: qdrant/qdrant:latest
    restart: unless-stopped
    expose:
      - "6333"
    ports:
      - "6333:6333"
    volumes:
      - qdrant:/qdrant/storage:z

  # Redis is used for caching
  redis:
    container_name: news-fusion-redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

volumes:
  pg:
  qdrant:
  redis:
