name: Setup Environment
description: Prepare and install everything for repository

inputs:
  TOOLS_API_BASE_URL:
    required: true

runs:
  using: composite
  steps:      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        shell: bash
        run: bun install
        env:
          TOOLS_API_BASE_URL: ${{ inputs.TOOLS_API_BASE_URL }}
