import { Info } from 'lucide-react';

export default function AIDisclaimer() {
	return (
		// Add something to make this message seperate and more visible
		<footer className="font-mono text-sm items-center flex flex-row text-gray-500 dark:text-gray-400">
			<Info className="inline-block mr-2" size={16} />
			Disclaimer: Summaries are generated by AI, it may not be accurate.
		</footer>
	);
}
