name: Clean Database
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  Clean:
    name: Clean
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.12"

      - run: uv pip install -r requirements.txt

      - run: python -m scripts.remove_expired_news
        env:
            LOGURU_LEVEL: "INFO"
            REDIS_URL: ${{ secrets.REDIS_URL }}
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
            QDRANT_CONNECTION_STRING: ${{ secrets.QDRANT_CONNECTION_STRING }}
