name: Crawl News
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  Crawl:
    name: Crawl
    runs-on: self-hosted
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.12"

      - run: uv pip install -r requirements.txt

      - run: uv run crawl.py --check-youtube
        env:
            LOGURU_LEVEL: "INFO"

            REDIS_URL: ${{ secrets.REDIS_URL }}
            DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}

            DATABASE_URL: ${{ secrets.DATABASE_URL }}

            QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
            QDRANT_CONNECTION_STRING: ${{ secrets.QDRANT_CONNECTION_STRING }}

            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            OPENAI_API_BASE_URL: ${{ secrets.OPENAI_API_BASE_URL }}
            OPENAI_CHAT_MODEL: ${{ secrets.OPENAI_CHAT_MODEL }}
