name: Publish Docker image

on:
  # push:
  #   tags:
  #     - v*
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 'Build Inventory Image'
        run: |
          docker build -f ./docker/Dockerfile . --tag ghcr.io/ckt1031/news-fusion-server:latest
          docker push ghcr.io/ckt1031/news-fusion-server:latest